[package]
name = "comuicate_machines"
version = "0.1.0"
authors = ["Prometeo <xairi.valdivia@gmail.com>"]
edition = "2018"

[dependencies]
atty = "0.2.11"
serde_json = "1.0.39"
structopt = { version = "0.2", default-features = false }